[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Allow writing SVG preview files and simulation output
fs_permissions = [
    { access = "read-write", path = "./svg-preview" },
    { access = "read-write", path = "./simulation-output" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
